### ISSUE TITLE
Add method to handle nulls when parsing

### ISSUE THREAD

**Issue by bladeoflight16** [arogozine/EnumUtilities#9]
Sometimes, you need to parse an enum but might have a null value:

```
string myVal = null;
MyEnum? e = null == myVal ? null : EnumUtil.Parse<MyEnum>(myVal);
```

This is clunky and verbose. A convenience method would clean it up quite a bit:

```
string myVal = null;
MyEnum? e = EnumUtil.ParseNullable<MyEnum>(myVal);
```

Its implementation would be fairly simple. It would look roughly like this:

```
public static T? ParseNullable<T>(string value) where T : struct, E
            => (T?)(null == value ? null : Enum.Parse(typeof(T), value));
```

An `ignoreCase` version would also be needed, of course.

**Comment by bladeoflight16** [comment]
It may or may not be a good idea to also treat the empty string this way:

```
public static T? ParseNullable<T>(string value) where T : struct, E
            => (T?)(String.IsNullOrEmpty(value) ? null : Enum.Parse(typeof(T), value));
```

**Comment by binki** [comment]
I like the name you edited in (`ParseNullable`).

My opinion is that by default the empty string should be treated differently than `null`. Otherwise, what is the point in distinguishing between empty string and `null`? Empty string means someone meant to provide the value but write it wrong whereas they would have passed `null` if they meant it.

You can write your own `StringUtil.NullIfEmpty(string s)` helper and use that, perhaps? Or add another parameter `bool ignoreEmpty` which defaults to `false`?

**Comment by bladeoflight16** [comment]
@binki  Having thought about it, I'm inclined to agree that empty string should be treated differently unless the caller indicates otherwise. A separate method might make the most sense, but I'm again at a bit of a loss for a name. `ParseNullableEmptyAsNull` comes to mind but is of course far too verbose.

**Comment by arogozine** [comment]
I might add a `ParseAsNullable` or something as part of the move to .NET Standard and C# 7.3

**Comment by arogozine** [comment]
Looks like Enums .NET is the go to enum parser at the moment. I am planning on archiving this project and pointing to Enums .NET.
